name: time_capsule_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  provider: ^6.0.5
  cupertino_icons: ^1.0.8
  postgres: ^2.5.3
  bcrypt: ^1.1.3
  lottie: ^3.3.1
  intl: ^0.20.2
  logger: ^2.3.0
  flutter_local_notifications: ^19.4.0
  timezone: ^0.10.0
  workmanager: ^0.9.0+2
  shared_preferences: ^2.5.3
  image_picker: ^0.8.7+5
  file_selector: ^0.9.0
  share_plus: ^10.0.2
  permission_handler: ^11.2.0
  fluttertoast: ^8.2.12
  flutter_secure_storage: ^9.0.0
  flutter_localization: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animation/Panda.json
    - assets/animation/Kawaii emoji saying hi.json
    - assets/icons/icon.png
    - assets/icons/splash.jpg
    - assets/.env
    - assets/translations/
    - assets/images/

